import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { afterAll, expect, it, onTestFailed } from 'vitest';
import { chromium, type Browser, type Page } from 'playwright';
import { launchWebScaffold, type WebScaffold } from './scaffold.ts';
import type { SessionEvent } from '@deepseek-ai/dsh-session';
import { credentialRef } from '@deepseek-ai/dsh-credentials';
import { prepareReplay } from './remote-replay.ts';
import { newEnglishPage } from './support.ts';

const root = process.env.DSH_REMOTE_ROOT!;
const state = process.env.DSH_REMOTE_STATE!;
let scaffold: WebScaffold | undefined;
let browser: Browser | undefined;
const browserErrors: string[] = [];
let replay: Awaited<ReturnType<typeof prepareReplay>> | undefined;
afterAll(async () => { try { await browser?.close(); await scaffold?.close(); } finally { await replay?.close(); } });
it('keeps portable workspaces isolated across the Web lifecycle and failures', async () => {
  replay = await prepareReplay(state);
  const key = credentialRef('DSH_REMOTE_SEARCH_TEST');
  const launch = (providersOnly = false) => launchWebScaffold({ extraOverlayPath: `${root}/integrations/dsh/profiles/remote/cordis.patch.yml`,
    extraInstallAnchors: [`${root}/target/web-profile/package.json`],
    compareReplaySession: false, ...(providersOnly ? {} : {
      replayFixture: new URL('../../../snapshots/web/web-search-round/session.v2.jsonl', import.meta.url).pathname, replayOverride: replay.override }), deepSeekSearch: { baseURL: replay.baseURL, apiKeyEnv: key },
    directoryPicking: false, persistentStateRoot: state, harnessHome: `${state}/home`,
    agentPresets: { default: 'remote', roots: [{ path: `${root}/target/web-plugin/presets`, trust: 'system' }] }, toolsMode: 'native' });
  scaffold = await launch();
  await expect(scaffold.ctx.get('sessionController').openWorkspacePath({ path: '/workspace' }, new AbortController().signal)).rejects.toThrow('Native workspace opening is disabled');
  await scaffold.ctx.credentials.set(key, 'local-connector-fixture');
  browser = await chromium.launch({ headless: true });
  let page = await openPage(browser);
  onTestFailed(async () => { if (page.isClosed()) return; console.error('PAGE', await page.locator('body').innerText()); await page.screenshot({ path: `${root}/target/web-failure.png`, fullPage: true }); });
  await page.goto(scaffold.authenticatedUrl);
  await page.getByLabel('World', { exact: true }).selectOption('a');
  await page.getByLabel('Remote directory', { exact: true }).fill('/workspace');
  await page.getByRole('button', { name: 'Add portable workspace', exact: true }).click();
  await expect.poll(() => scaffold!.ctx.agents.list().length, { timeout: 30000 }).toBe(1);
  await page.getByLabel('World', { exact: true }).selectOption('b');
  await page.getByRole('button', { name: 'Add portable workspace', exact: true }).click();
  await expect.poll(() => scaffold!.ctx.agents.list().length, { timeout: 30000 }).toBe(2);
  await expect.poll(() => page.getByRole('button', { name: /New session in World/ }).count(), { timeout: 15000 }).toBe(2);
  await page.screenshot({ path: `${root}/target/web-two-worlds.png`, fullPage: true });
  const first = scaffold.ctx.agents.list()[0]!;
  await page.getByRole('button', { name: `Open session ${first.session.header.id}`, exact: true }).click();
  const settled = scaffold.whenTurnSettled();
  const input = page.locator('[data-composer-input][contenteditable=true]').first();
  const results: Extract<SessionEvent, { type: 'tool/result' }>[] = [];
  scaffold.ctx.on('session/event', (_session, event) => { if (event.type === 'tool/result') results.push(event); });
  await input.fill('Exercise the remote workspace and the local search connector.');
  await input.press('Enter');
  await settled;
  expect(results).toHaveLength(8);
  for (const result of results) expect(result.data.message.content, JSON.stringify(result)).toEqual(expect.arrayContaining([expect.objectContaining({ isError: false })]));
  expect(replay.requests).toHaveLength(1);
  expect(replay.requests[0]).toMatchObject({ url: '/messages', key: 'local-connector-fixture' });
  const owner = scaffold.ctx.get('executionWorlds').forAgent(first);
  expect(await owner.fs.readText(await owner.fs.resolve('browser-proof.txt'))).toBe('browser-proof');
  expect(await owner.fs.readText(await owner.fs.resolve('coding-0.txt'))).toBe('after\n');
  const second = scaffold.ctx.agents.list()[1]!;
  const other = scaffold.ctx.get('executionWorlds').forAgent(second);
  expect(await other.fs.stat(await other.fs.resolve('browser-proof.txt'))).toBeUndefined();
  expect(await other.fs.stat(await other.fs.resolve('coding-0.txt'))).toBeUndefined();
  await page.screenshot({ path: `${root}/target/web-remote-round.png`, fullPage: true });
  const sessionId = first.session.header.id;
  await page.getByRole('button', { name: 'Branch into a new conversation' }).last().click();
  await expect.poll(() => scaffold!.ctx.agents.list().find(agent => agent.session.header.parentSession === sessionId), { timeout: 15000 }).toBeDefined();
  const fork = scaffold.ctx.agents.list().find(agent => agent.session.header.parentSession === sessionId)!;
  expect(scaffold.ctx.get('executionWorlds').bindings.get(fork.session.header.id)).toEqual(scaffold.ctx.get('executionWorlds').bindings.get(sessionId));
  await page.getByRole('button', { name: `Open session ${sessionId}`, exact: true }).click();
  const deepLink = new URL(page.url());
  const oldRuntime = owner.remoteWorld.client.info.runtime;
  await page.close();
  await scaffold.close();
  await replay.roundScript();
  scaffold = await launch();
  page = await openPage(browser);
  await page.goto(scaffold.authenticatedUrl);
  await page.goto(new URL(deepLink.pathname + deepLink.search + deepLink.hash, scaffold.baseUrl).href);
  await expect.poll(() => page.getByRole('button', { name: /New session in World/ }).count(), { timeout: 15000 }).toBe(2);
  const coldSettled = scaffold.whenTurnSettled();
  results.length = 0;
  scaffold.ctx.on('session/event', (_session, event) => { if (event.type === 'tool/result') results.push(event); });
  await page.locator('[data-composer-input][contenteditable=true]').first().fill('Continue in the saved World.');
  await page.locator('[data-composer-input][contenteditable=true]').first().press('Enter');
  expect(await coldSettled).toBe(sessionId);
  expect(results).toHaveLength(8);
  for (const result of results) expect(result.data.message.content, JSON.stringify(result)).toEqual(expect.arrayContaining([expect.objectContaining({ isError: false })]));
  const resumed = scaffold.ctx.agents.get(sessionId)!;
  const resumedOwner = scaffold.ctx.get('executionWorlds').forAgent(resumed);
  expect(resumedOwner.remoteWorld.client.info.runtime).not.toBe(oldRuntime);
  expect(await resumedOwner.fs.readText(await resumedOwner.fs.resolve('world.txt'))).toBe('a\n');
  expect(replay.requests).toHaveLength(2);
  await page.close();
  await scaffold.close();
  await replay.cancelScript();
  scaffold = await launch();
  page = await openPage(browser);
  await page.goto(scaffold.authenticatedUrl);
  await page.goto(new URL(deepLink.pathname + deepLink.search + deepLink.hash, scaffold.baseUrl).href);
  const canceled = scaffold.whenTurnSettled();
  await page.locator('[data-composer-input][contenteditable=true]').first().fill('Start the cancellable remote command.');
  await page.locator('[data-composer-input][contenteditable=true]').first().press('Enter');
  await expect.poll(async () => {
    const agent = scaffold!.ctx.agents.get(sessionId);
    if (!agent) return false;
    const world = scaffold!.ctx.get('executionWorlds').forAgent(agent);
    return !!await world.fs.stat(await world.fs.resolve('cancel.started'));
  }, { timeout: 20000 }).toBe(true);
  await page.getByRole('button', { name: 'Stop generating', exact: true }).click();
  expect(await canceled).toBe(sessionId);
  const cancelOwner = scaffold.ctx.get('executionWorlds').forAgent(scaffold.ctx.agents.get(sessionId)!);
  expect(await cancelOwner.fs.stat(await cancelOwner.fs.resolve('cancel.finished'))).toBeUndefined();
  const pid = (await cancelOwner.fs.readText(await cancelOwner.fs.resolve('cancel.pid'))).trim();
  expect(pid).toMatch(/^\d+$/);
  const probe = cancelOwner.subprocess.spawn({ argv: ['bash', '-c', 'kill -0 "$1" 2>/dev/null', 'probe', pid], cwd: '/workspace',
    stdio: { stdin: 'ignore', stdout: { maxBytes: 1024 }, stderr: { maxBytes: 1024 } }, graceMs: 500 });
  expect((await probe.done).exitCode).not.toBe(0);
  await probe.waitForExit();
  await page.screenshot({ path: `${root}/target/web-cold-cancel.png`, fullPage: true });
  await page.close();
  await scaffold.close();
  const bindingFile = `${state}/bindings.json`;
  const bindings = JSON.parse(await readFile(bindingFile, 'utf8'));
  bindings.sessions = bindings.sessions.filter((entry: { sessionId: string }) => entry.sessionId !== sessionId);
  await writeFile(bindingFile, JSON.stringify(bindings), { mode: 0o600 });
  scaffold = await launch(true);
  page = await openPage(browser);
  await page.goto(scaffold.authenticatedUrl);
  await page.goto(new URL(deepLink.pathname + deepLink.search + deepLink.hash, scaffold.baseUrl).href);
  const refusal = page.waitForResponse(response => response.request().postData()?.includes('This must fail without a saved binding.') ?? false);
  await page.locator('[data-composer-input][contenteditable=true]').first().fill('This must fail without a saved binding.');
  await page.locator('[data-composer-input][contenteditable=true]').first().press('Enter');
  expect(await (await refusal).text()).toMatch(/saved Session membership/);
  await expect.poll(() => page.locator('body').innerText(), { timeout: 15000 }).toMatch(/WORLD_REQUIRED|Session admission failed|saved Session membership/);
  expect(scaffold.ctx.agents.get(sessionId)).toBeUndefined();
  expect(scaffold.ctx.get('executionWorlds').bindings.get(sessionId)).toBeUndefined();
  await page.screenshot({ path: `${root}/target/web-missing-binding.png`, fullPage: true });
  const containers = JSON.parse(process.env.DSH_TEST_WORLD_CONTAINERS!);
  execFileSync('docker', ['stop', containers.b], { stdio: 'ignore' });
  const secondId = second.session.header.id;
  await page.getByRole('button', { name: `Open session ${secondId}`, exact: true }).click();
  const unavailable = page.waitForResponse(response => response.request().postData()?.includes('This must fail for an unavailable World.') ?? false);
  await page.locator('[data-composer-input][contenteditable=true]').first().fill('This must fail for an unavailable World.');
  await page.locator('[data-composer-input][contenteditable=true]').first().press('Enter');
  expect(await (await unavailable).text()).toMatch(/Remote control command failed/);
  expect(scaffold.ctx.agents.get(secondId)).toBeUndefined();
  expect(scaffold.ctx.get('executionWorlds').bindings.get(secondId)).toBeDefined();
  expect(browserErrors).toEqual([]);
});

async function openPage(browser: Browser): Promise<Page> {
  const page = await newEnglishPage(browser);
  page.on('console', message => { if (['error', 'warning'].includes(message.type())) { console.error('CONSOLE', message.text()); if (message.text().includes('event feed subscriber failed')) browserErrors.push(message.text()); } });
  page.on('pageerror', error => { browserErrors.push(String(error)); console.error('BROWSER', error); });
  return page;
}
